<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.l2t</groupId>
    <artifactId>java_ws_project</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0</version>
    <modules>
        <module>learning_core_java</module>
        <module>dice_game</module>
        <module>learning_json</module>
        <module>ipl-stats</module>
        <module>invoice_gen_service</module>
        <module>employee-app</module>
        <module>movie_recommendation</module>
        <module>learning-sql</module>
        <module>learning_jdbc_app</module>
        <module>cbook-server-app</module>
        <module>learning-spring-core</module>
        <module>invoice-gen-app</module>
    </modules>


</project>