spring.application.name=cbook-server-app

spring.datasource.url=jdbc:postgresql://dpg-d5vds2ali9vc73a698o0-a.virginia-postgres.render.com:5432/l2tdb_6ots
spring.datasource.username=adminuser
spring.datasource.password=4UYhQ6RxvHB3oJ3EJhoKA1JWHAXbuAIU

server.port=8090

